"""
What the Homebrew formula says, checked without installing anything.

The formula is generated by `scripts/build_homebrew_formula.py` from what PyPI
published, so the digests in it are only ever as right as the index was - that
part is not this suite's business, and neither is running `brew`. What is
checked here is the agreement between the formula, the generator and the rest
of the project: a class name Homebrew derives from the file name, a resource
list that matches the runtime imports, and a `test do` block asserting
behaviour the plugin actually has.

A formula that gets one of those wrong installs fine and fails on somebody
else's laptop, which is the one place nobody here would see it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

import build_homebrew_formula as builder

ROOT = Path(__file__).resolve().parents[1]
FORMULA = ROOT / "packaging" / "homebrew" / "check-opencloud-security.rb"


@pytest.fixture(scope="module")
def formula() -> str:
    return FORMULA.read_text(encoding="utf-8")


def test_the_formula_is_committed():
    """
    A tap installs the file, not the generator. If it is missing, the install
    instructions in docs/installation.md point at nothing.
    """
    assert FORMULA.is_file(), f"{FORMULA.relative_to(ROOT)} has not been generated"


def test_the_class_name_is_the_one_homebrew_derives_from_the_file_name(formula):
    """
    Homebrew requires the class to match the file name with the hyphens taken
    out and each word capitalised, and refuses to load the formula otherwise.
    """
    expected = "".join(part.capitalize() for part in FORMULA.stem.split("-"))

    assert f"class {expected} < Formula" in formula
    assert builder.FORMULA_CLASS == expected


def test_every_runtime_import_has_a_resource(formula):
    """
    virtualenv_install_with_resources installs only what the formula lists, so
    a missing resource is an ImportError the first time the check runs.
    """
    listed = set(re.findall(r'^  resource "([^"]+)" do$', formula, flags=re.MULTILINE))

    assert listed == set(builder.RESOURCES)


def test_the_stub_package_is_not_a_resource(formula):
    """
    `types-requests` is in the wheel's metadata and has nothing to import.
    packaging/nfpm.yaml leaves it out of the .deb and the .rpm for the same
    reason; a formula that pulled it in would build a larger venv for nothing.
    """
    assert "types-requests" not in formula
    assert "types-requests" not in builder.RESOURCES


def test_every_resource_pins_a_url_and_a_digest(formula):
    """An unpinned resource is an unreviewed download on somebody's machine."""
    blocks = re.findall(
        r'  resource "[^"]+" do\n    url "([^"]+)"\n    sha256 "([0-9a-f]{64})"\n  end',
        formula,
    )

    assert len(blocks) == len(builder.RESOURCES)
    for url, _digest in blocks:
        assert url.startswith("https://files.pythonhosted.org/")
        assert url.endswith(".tar.gz"), "a formula builds from source, not from a wheel"


def test_the_formula_builds_from_a_source_distribution(formula):
    """
    Same reason as the resources: a wheel URL would pin one platform's tag
    into a file that has to work on macOS and on Linux.
    """
    url = re.search(r'^  url "([^"]+)"$', formula, flags=re.MULTILINE)

    assert url is not None
    assert url.group(1).endswith(".tar.gz")


def test_the_python_dependency_is_a_formula_homebrew_actually_has(formula):
    """
    `python3` is not a formula name. The dependency has to name a keg, and it
    has to stay at or above the project's own requires-python floor.
    """
    assert f'depends_on "{builder.PYTHON_FORMULA}"' in formula

    major, minor = builder.PYTHON_FORMULA.removeprefix("python@").split(".")
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    floor = re.search(r'requires-python\s*=\s*">=([0-9]+)\.([0-9]+)"', pyproject)
    assert floor is not None
    assert (int(major), int(minor)) >= (int(floor.group(1)), int(floor.group(2)))


def test_the_formula_test_block_asserts_the_version_it_pinned(formula):
    """
    Asserting the entry point runs is not enough on its own: another copy on
    PATH would satisfy it. The version ties the assertion to this build.
    """
    version = re.search(r"check_opencloud_security-([0-9][^/]*)\.tar\.gz", formula)
    assert version is not None

    assert f'assert_match "{version.group(1)}", shell_output' in formula


def test_the_formula_test_block_expects_the_unknown_exit_code(formula):
    """
    A check that cannot reach its instance exits 3, not 0 and not a traceback.
    The formula asserts the same contract the plugin's own tests do - and does
    it against a name reserved by RFC 2606, so `brew test` contacts nobody.
    """
    assert "opencloud.invalid" in formula
    assert '2>&1", 3' in formula
    assert 'assert_match "UNKNOWN", output' in formula


def test_the_formula_says_it_is_generated(formula):
    """A hand-edit that gets a digest wrong fails on a stranger's machine."""
    assert formula.startswith("# Generated by scripts/build_homebrew_formula.py")


def test_the_description_fits_what_homebrew_audits(formula):
    """
    `brew audit` caps desc at 80 characters and rejects one that opens with the
    formula's own name or with an article.
    """
    desc = re.search(r'^  desc "([^"]+)"$', formula, flags=re.MULTILINE)

    assert desc is not None
    assert len(desc.group(1)) <= 80
    assert not desc.group(1).lower().startswith(("check-opencloud", "a ", "an ", "the "))
