#!/usr/bin/env python3
"""Generate local frontend pages from the CLI's Markdown documentation."""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

import markdown

from webapp.documentation import DOCUMENTATION_BY_SLUG, DOCUMENTATION_PAGES

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "frontend" / "templates" / "docs"
PROJECT_URL = "https://github.com/sowoi/check-opencloud-security"
GENERATED_MARKER = "{# Generated by scripts/build_frontend_documentation.py. #}"
MARKDOWN_EXTENSIONS = ("fenced_code", "tables", "sane_lists", "toc")


def _section(source: str, start: str | None, end: str | None) -> str:
    """Select the configured heading range and drop a duplicate page title."""
    if start is not None:
        marker = f"{start}\n"
        if marker not in source:
            raise ValueError(f"start heading not found: {start}")
        source = marker + source.split(marker, 1)[1]
    if end is not None:
        marker = f"\n{end}\n"
        if marker not in source:
            raise ValueError(f"end heading not found: {end}")
        source = source.split(marker, 1)[0]

    # The frontend supplies the one h1. Full-document sources start with the
    # same title, while a selected README range keeps its first section and
    # demotes it below the page title later.
    if start is None:
        source = re.sub(r"\A# [^\n]+\n+", "", source, count=1)
    source = re.split(r"\n## Trademarks and affiliation\n", source, maxsplit=1)[0]
    return source.rstrip() + "\n"


def _demote_headings(source: str) -> str:
    """Move README's top-level sections below the frontend's h1."""
    return re.sub(r"^(#{1,5})(?= )", r"#\1", source, flags=re.MULTILINE)


def _rewrite_relative_links(body: str, source_path: str) -> str:
    """Keep links between generated documents inside the frontend."""
    source_dir = Path(source_path).parent
    local = {
        str((REPO_ROOT / page.source).resolve()): page.slug
        for page in DOCUMENTATION_PAGES
    }

    def rewrite(match: re.Match[str]) -> str:
        raw = html.unescape(match.group(1))
        parts = urlsplit(raw)
        if parts.scheme or parts.netloc or not parts.path:
            return match.group(0)
        resolved = str((REPO_ROOT / source_dir / parts.path).resolve())
        if resolved == str((REPO_ROOT / "docs" / "README.md").resolve()):
            target = "/documentation"
            if parts.fragment:
                target += f"#{parts.fragment}"
            return f'href="{html.escape(target, quote=True)}"'
        slug = local.get(resolved)
        if slug is not None:
            target = f"/documentation/{slug}"
        else:
            try:
                repository_path = Path(resolved).relative_to(REPO_ROOT)
            except ValueError:
                return match.group(0)
            target = f"{PROJECT_URL}/blob/main/{repository_path.as_posix()}"
        if parts.fragment:
            target += f"#{parts.fragment}"
        return f'href="{html.escape(target, quote=True)}"'

    return re.sub(r'href="([^"]+)"', rewrite, body)


def _escape_jinja(body: str) -> str:
    """Make examples such as GitHub expressions inert inside Jinja."""
    return (
        body.replace("{{", "&#123;&#123;")
        .replace("}}", "&#125;&#125;")
        .replace("{%", "&#123;%")
        .replace("%}", "%&#125;")
        .replace("{#", "&#123;#")
        .replace("#}", "#&#125;")
    )


# A page short enough to scan in one or two screens does not need a jump
# list; one long enough to have this many top-level sections does.
MIN_TOC_SECTIONS = 5


def _table_of_contents(body: str) -> str:
    """A jump list of a page's own top-level sections, or "" below the threshold."""
    headings = re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body, flags=re.DOTALL)
    if len(headings) < MIN_TOC_SECTIONS:
        return ""
    links = "\n".join(
        f'  <a href="#{anchor}" lang="en">{text}</a>' for anchor, text in headings
    )
    return (
        '<nav class="docs-toc card section-gap" '
        "aria-label=\"{{ t('docs.guide.toc.aria') }}\" data-reveal>\n"
        "  <p class=\"kicker\">{{ t('docs.guide.toc.heading') }}</p>\n"
        f"{links}\n"
        "</nav>\n"
    )


def render_page(slug: str) -> str:
    """Render one manifest entry as a complete Jinja template."""
    page = DOCUMENTATION_BY_SLUG[slug]
    source = (REPO_ROOT / page.source).read_text(encoding="utf-8")
    selected = _section(source, page.start_heading, page.end_heading)
    if page.demote_headings:
        selected = _demote_headings(selected)
    body = markdown.markdown(
        selected,
        extensions=list(MARKDOWN_EXTENSIONS),
        output_format="html5",
    )
    # Python-Markdown's table extension writes `style="text-align: ..."` on
    # every cell. The frontend CSP rejects inline style and the design system
    # already owns alignment, so generated prose must not carry it through.
    body = re.sub(r'\s+style="[^"]*"', "", body)
    body = _rewrite_relative_links(body, page.source)
    body = _escape_jinja(body)
    toc = _table_of_contents(body)
    toc_block = f"{toc}\n" if toc else ""
    # The chrome is translated from the catalogue; the guide itself is the
    # repository's own English Markdown, and the notice above it says so
    # rather than letting a reader assume the page failed to translate.
    return f"""{GENERATED_MARKER}
{{% extends "base.html" %}}

{{% block title %}}{{{{ t('docs.{page.slug}.title') }}}}{{% endblock %}}
{{% block description %}}{{{{ t('docs.{page.slug}.description') }}}}{{% endblock %}}

{{% block content %}}
<section class="page-head">
  <p class="kicker">{{{{ t('docs.guide.kicker') }}}}</p>
  <h1>{{{{ t('docs.{page.slug}.title') }}}}</h1>
  <p class="lede">{{{{ t('docs.{page.slug}.description') }}}}</p>
</section>

{{% if locale != 'en' %}}
<p class="hint section-gap" lang="{{{{ locale }}}}">{{{{ t('docs.guide.english_notice') }}}}</p>
{{% endif %}}

{toc_block}<article class="docs-article card section-gap" data-reveal lang="en">
{body}
</article>

{{% include "_page-nav.html" %}}
{{% endblock %}}
"""


def generated_pages() -> dict[Path, str]:
    """Every generated path and the exact content it should carry."""
    return {
        OUTPUT_DIR / f"{page.slug}.html": render_page(page.slug)
        for page in DOCUMENTATION_PAGES
    }


def write_pages() -> None:
    """Write the manifest and remove generated pages no longer in it."""
    expected = generated_pages()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in OUTPUT_DIR.glob("*.html"):
        if path not in expected and path.read_text(encoding="utf-8").startswith(
            GENERATED_MARKER
        ):
            path.unlink()
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")


def stale_pages() -> list[Path]:
    """Return missing, stale or retired generated pages."""
    expected = generated_pages()
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    if OUTPUT_DIR.exists():
        stale.extend(
            path
            for path in OUTPUT_DIR.glob("*.html")
            if path not in expected
            and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
        )
    return sorted(set(stale))


def main() -> int:
    """Generate pages, or verify that the checked-in copies are current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a generated page differs instead of writing it",
    )
    args = parser.parse_args()
    if args.check:
        stale = stale_pages()
        if stale:
            for path in stale:
                print(path.relative_to(REPO_ROOT), file=sys.stderr)
            print(
                "Frontend documentation is stale; run "
                "python scripts/build_frontend_documentation.py",
                file=sys.stderr,
            )
            return 1
        return 0
    write_pages()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
