# Generated by scripts/build_homebrew_formula.py - do not edit by hand.
#
# Regenerate after every release: the version, the URLs and every sha256 here
# describe artifacts PyPI has already published, and a hand-edit that gets one
# digest wrong fails at `brew install` on somebody else's machine.
class CheckOpencloudSecurity < Formula
  include Language::Python::Virtualenv

  desc "Check the security level of your OpenCloud instance with a built-in scanner"
  homepage "https://github.com/sowoi/check-opencloud-security"
  url "https://files.pythonhosted.org/packages/30/71/5ff366bd76b2c68a835088a1ed7885b1096c19ef5a172f0946ded44c9b8a/check_opencloud_security-1.20.0.tar.gz"
  sha256 "e23c53dc0977f941aa1d28630a9349a12ea6fe95c5f8e2280deb54fcc10cc150"
  license "GPL-3.0-or-later"

  depends_on "python@3.13"

  resource "certifi" do
    url "https://files.pythonhosted.org/packages/a3/c2/24167ea9858356b47a87a50d39908bfdb72ceeefe0041586e704e5376b3a/certifi-2026.7.22.tar.gz"
    sha256 "741e2c3b351ddf169a738da9f2c048608ff7f2c5cc02f1ebc6b118bb090d5d55"
  end

  resource "charset-normalizer" do
    url "https://files.pythonhosted.org/packages/e5/3f/143b048436775b0f76ac3eec145c019e8173ccc2885c8f20319b996d5e83/charset_normalizer-3.5.1.tar.gz"
    sha256 "6117b84ea48435e5356dc737f5121485c30920ba43375fa7b434fd753df0eac3"
  end

  resource "idna" do
    url "https://files.pythonhosted.org/packages/5f/f7/abb373e5757eaec4b922b92f97ec8d6d7e057cf06778247604fbc4e7c3f3/idna-3.19.tar.gz"
    sha256 "5e0811a4383b21dc5838069f801c4fb62113b7447663d2530d2bd6e77b49bf15"
  end

  resource "PyYAML" do
    url "https://files.pythonhosted.org/packages/05/8e/961c0007c59b8dd7729d542c61a4d537767a59645b82a0b521206e1e25c2/pyyaml-6.0.3.tar.gz"
    sha256 "d76623373421df22fb4cf8817020cbb7ef15c725b9d5e45f17e189bfc384190f"
  end

  resource "requests" do
    url "https://files.pythonhosted.org/packages/ac/c3/e2a2b89f2d3e2179abd6d00ebd70bff6273f37fb3e0cc209f48b39d00cbf/requests-2.34.2.tar.gz"
    sha256 "f288924cae4e29463698d6d60bc6a4da69c89185ad1e0bcc4104f584e960b9ed"
  end

  resource "urllib3" do
    url "https://files.pythonhosted.org/packages/53/0c/06f8b233b8fd13b9e5ee11424ef85419ba0d8ba0b3138bf360be2ff56953/urllib3-2.7.0.tar.gz"
    sha256 "231e0ec3b63ceb14667c67be60f2f2c40a518cb38b03af60abc813da26505f4c"
  end

  def install
    virtualenv_install_with_resources
  end

  test do
    # Two assertions, because either alone passes for the wrong reason: the
    # first proves the entry point runs at all, the second that the version it
    # reports is the one this formula built rather than another copy on PATH.
    assert_match "1.20.0", shell_output("#{bin}/check-opencloud-security --version")

    # A check that cannot reach its instance must still be a check: it exits 3
    # (UNKNOWN), the Nagios code for "measured nothing", rather than crashing
    # or inventing a verdict. `.invalid` is reserved by RFC 2606 and resolves
    # nowhere, so this makes no request to anybody's server during the test.
    output = shell_output(
      "#{bin}/check-opencloud-security --host opencloud.invalid --timeout 5 2>&1", 3
    )
    assert_match "UNKNOWN", output
  end
end
